--INSERT
--Si queremos darle valores a todos los campos.
INSERT INTO DEPART VALUES(50,'INFORM�TICA','HUELVA');



--OTRA MANERA
--Si queremos darle valores solo a algunos campos.
INSERT INTO DEPART(DEPT_NO, DNOMBRE, LOC)
		VALUES (60,'COMPRAS','M�LAGA');
		
INSERT INTO DEPART(DEPT_NO, DNOMBRE)
		VALUES (70, 'FORMACI�N');

		
--UPDATE

UPDATE DEPART
SET LOC='C�DIZ'
WHERE DEPT_NO=60;

--DELETE

DELETE DEPART
WHERE LOC IS NULL;


--TEORIA
PREGUNTA DEL INSERT MENOS LA DEL INSERT SELECT .

UPDATE Y DELETE ENTERO.

--EJERCICIOS
CASO PRACTICO 1 Y 3.
ACTIVIDADES PROPUESTAS 1 Y 3.

CARGAR TABLASUNI3 Y TABLASUNI5.





